# -*- coding: utf-8 -*-
"""A101_Dini Aulia Putri_Basic Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKA3CX51_RNPyXHbLrwVnx1l6laYQujK
"""

# Membuat dictionary untuk biodata
biodata = {
    "Nama": "Dini Aulia Putri",
    "Umur": 23,
    "Agama": "Islam",
    "Alamat": {
        "Desa": "Naras 1",
        "Kota": "Pariaman",
        "Provinsi": "Sumatera Barat"
    },
    "Status": "Freshgraduate",
    "Program_Studi": "Pendidikan Fisika",
    "Universitas": "Universitas Negeri Padang",
    "Warna_Kesukaan": "Biru",
    "Alasan_Mengikuti_Bootcamp": "Ingin mengembangkan kemampuan analisis data, memperluas wawasan di bidang teknologi, dan meningkatkan peluang karir di era digital."
}

# Menampilkan biodata
for key, value in biodata.items():
    if isinstance(value, dict):
        print(f"{key}:")
        for sub_key, sub_value in value.items():
            print(f"  {sub_key}: {sub_value}")
    else:
        print(f"{key}: {value}")